name = "btree-viewer"
version = "0.1.0"
license = "license"
author = "catalincd"
maintainer = "cc.dumitrescu02@gmail.com"
copyright = "Copyright 2022, catalincd"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
[dependencies]
gtk-fortran = { git = "https://github.com/vmagnin/gtk-fortran.git", branch = "gtk4" }
M_strings = { git = "https://github.com/urbanjost/M_strings.git" ,tag="v1.0.1"}
